services:
  - type: web
    name: chao-phone-repair
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///repair_shop.db
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
